### ISSUE TITLE
Unused variable `BUILT_LIBS_OBJ`

### ISSUE THREAD

**Issue by albinahlback** [pythar-chalmers/libmd407#15]
First off, thanks for sharing this repository.

When trying to make my fork more modular and more GNU-compatible, I noticed the unused variable `BUILT_LIBS_OBJ` here:
https://github.com/pythar-chalmers/libmd407/blob/4eda08e5b95c01e26af053e3c421eeeef7841ef9/Makefile#L48

Is it supposed to be replaced by something perhaps?

**Comment by almqv** [comment]
> First off, thanks for sharing this repository.
> 
> When trying to make my fork more modular and more GNU-compatible, I noticed the unused variable `BUILT_LIBS_OBJ` here:
> 
> https://github.com/pythar-chalmers/libmd407/blob/4eda08e5b95c01e26af053e3c421eeeef7841ef9/Makefile#L48
> 
> Is it supposed to be replaced by something perhaps?

Yes, that is old and not used anymore.

Feel free to make a PR :)
